lang: pt-BR

project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Introdução à Ciência de Dados para Administração"
  subtitle: "Fundamentos, Técnicas e Aplicações"
  cover-image: img/capa/capa.png
  author: "Washington Santos da Silva"
  date: 2026-01-19
  date-format: long
  chapters:
    - index.qmd
    - introducao.qmd

    - part: "Parte 1"
      chapters:
        - parte1.qmd
        - 01_capitulo.qmd
        - 02_capitulo.qmd
        - 03_capitulo.qmd
        - 04_capitulo.qmd
        - 05_capitulo.qmd
    - part: "Parte 2"
      chapters:
        - parte2.qmd
        - 06_capitulo.qmd

    - referencias.qmd

bibliography: referencias.bib
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
  pdf:
    documentclass: scrreprt



